### ISSUE TITLE
Remove new line character after link text

### ISSUE THREAD

**Issue by edison23** [igorlogius/copy-tabs#7]
**Describe the bug**
With the Copy selected tabs as links, the link contains a new line character after the hyperlink. This forces user to pres backspace every time they paste the link somewhere. Could possibly trigger unwanted send in messengers.

**To Reproduce**
1. Copy tab as link
2. Paste the hyperlink (ie., [tab title](taburl)) anywhere (even plain text editor like Sublime text where you get only the tab title (desired)
3. Observe the cursor jump on next line because of the new line character after the link

**Expected behavior**
No new line character after copied link, cursor stays right after the link

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 21H2 19044.3208, Kubuntu 22.04 latest stable updates as of 2023-07-20)
 - Firefox
 - 115.0.2 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
I have the action to copy the tab link mapped to `Alt-O` keyboard shortcut.
The whole issue applies also to text URL links. (I have that mapped to `Alt-Shift-O`)

**Comment by igorlogius** [comment]
Hi, thank you for taking the time to report this issue, 

you are absolutely right, the line ending handling slightly deviates depending on the mode, my bad. I'll fix that up to be consistent and align with expectations.

**Comment by igorlogius** [comment]
Should be fixed/consistent in version `1.13.39`

**Comment by edison23** [comment]
Awesome, thanks for the lightning fast reply and fix! ^__^ I confirm the issue is fixed now.
