### ISSUE TITLE
Add "Copy Tab as Link" and "Copy Tab as Text URL" options

### ISSUE THREAD

**Issue by gluttony38** [igorlogius/copy-tabs#8]
**Is your feature request related to a problem? Please describe.**
When a tab is selected, I can't copy another one, since from what I understood we can only copy all or selected, for example in this screenshot where I right clicked on first tab I want to copy the one I right clicked on:
![image](https://github.com/igorlogius/copy-tabs/assets/16116396/dbde43db-7921-45a5-a466-19623919643e)

**Describe the solution you'd like**
Add "Copy Tab as Link" and "Copy Tab as Text URL" options to be able to copy any tab whichever is selected. Maybe with a better wording but in screenshot we can see default options only use "Tab", with for example: "Reload Tab", "Mute Tab", "Pin Tab"...

**Describe alternatives you've considered**
The only alternative I think of is to switch to tab I want to copy then right click and select copy selected.

**Comment by igorlogius** [comment]
i'll see what i can do

**Comment by igorlogius** [comment]
Hope you like it. Have fun.

**Comment by igorlogius** [comment]
ref. https://addons.mozilla.org/en-US/firefox/addon/copy-tabs/reviews/2055886/

**Comment by gluttony38** [comment]
Great, thanks a lot !
